# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 paths:
   include:
     - app/*

pool:
 name: 'VmPool'

variables:
  - group: weather-app-secrets
steps:
- script: |
    python3.11 --version
    python3.11 -m pip install --upgrade pip setuptools
  displayName: "Use system Python 3.11"
- task: CopyFiles@2
  displayName: 'Move app contents to staging'
  inputs:
    sourceFolder: '$(System.DefaultWorkingDirectory)/app'
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/staging'

- task: ArchiveFiles@2
  displayName: "Archive Files"
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/staging'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'